// Code generated by hertz generator.

package Page

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pageindexMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pagecategoriesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _indexpageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _categoriespageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tagspageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __rchivespageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _categoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _categorypageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tagMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tagpageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _slugMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _nameMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _categorypostbypaginationpageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _indexbypaginationpageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tagpostbypaginationpageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchpageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _archivesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postpageMw() []app.HandlerFunc {
	// your code...
	return nil
}
