// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	blog_api "my_blog/biz/router/blog/api"
	blog_page "my_blog/biz/router/blog/page"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	blog_page.Register(r)

	blog_api.Register(r)
}
