// Code generated by hertz generator.

package main

import (
	"html/template"
	"os"

	"github.com/cloudwego/hertz/pkg/app/server"

	"my_blog/biz/interfaces/handler"
	"my_blog/biz/interfaces/middleware"
	"my_blog/biz/interfaces/middleware/static"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.SetFuncMap(map[string]any{
		"unescape": func(s string) template.HTML {
			return template.HTML(s)
		},
	})
	root := os.Getenv("ROOT_PATH")
	r.LoadHTMLGlob(root + "/templates/*")
	r.Static("/assets", root)
	r.Use(static.Serve("/admin", static.LocalFile(root+"/admin", false)))
	r.NoRoute(middleware.GetNoRouteMW()...)
	r.GET("/ping", middleware.RequestIdMW(), middleware.SessionMW(), middleware.AdminSessionMW(true), handler.Ping)

}
