// Code generated by hertz generator.

package main

import (
	"context"
	"fmt"
	"html/template"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"

	"my_blog/biz/infra/pkg/env"
	"my_blog/biz/interfaces/handler"
	"my_blog/biz/interfaces/middleware"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.SetFuncMap(map[string]any{
		"unescape": func(s string) template.HTML {
			return template.HTML(s)
		},
	})
	r.LoadHTMLGlob(fmt.Sprintf("%v/templates/*", env.RootPath()))
	r.Static("/assets", env.RootPath())
	r.StaticFS("/admin/", &app.FS{
		Root:       env.RootPath(),
		IndexNames: []string{"index.html"},
		PathNotFound: func(ctx context.Context, c *app.RequestContext) {
			c.File(fmt.Sprintf("%v/admin/index.html", env.RootPath()))
			c.Abort()
		},
	})
	r.NoRoute(middleware.GetNoRouteMW()...)
	r.GET("/ping", middleware.RequestIdMW(), middleware.SessionMW(), middleware.AdminSessionMW(), handler.Ping)

}
