// Code generated by hertz generator.

package main

import (
	"html/template"

	"github.com/cloudwego/hertz/pkg/app/server"

	"my_blog/biz/handler"
	"my_blog/biz/middleware"
	"my_blog/biz/middleware/static"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.SetFuncMap(map[string]any{
		"unescape": func(s string) template.HTML {
			return template.HTML(s)
		},
	})
	r.LoadHTMLGlob("../templates/*")
	r.Static("/assets", "../")
	r.Use(static.Serve("/admin", static.LocalFile("../admin", false)))
	r.NoRoute(middleware.GetNoRouteMW()...)
	r.GET("/ping", middleware.RequestIdMW(), middleware.SessionMW(), middleware.AdminSessionMW(true), handler.Ping)

}
