// Code generated by hertz generator.

package api

import (
	"context"

	api "my_blog/biz/model/blog/api"

	"github.com/cloudwego/hertz/pkg/app"
)

// HelloMethod .
// @router /test [GET]
func HelloMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.TestReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(api.TestResp)

	c.HTML(200, "", resp)
}
