// Code generated by hertz generator.

package api

import (
	"context"
	"net/http"

	serviceResp "my_blog/biz/common/resp"
	"my_blog/biz/model/blog/api"
	"my_blog/biz/service"

	"github.com/cloudwego/hertz/pkg/app"
)

// LoginAPI .
// @router /api/login [POST]
func LoginAPI(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.LoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(http.StatusBadRequest, serviceResp.NewParameterErrorResp())
		return
	}

	resp, err := service.LoginAPI(ctx, c, req)
	if err != nil {
		c.JSON(http.StatusInternalServerError, serviceResp.NewInternalErrorResp())
		return
	}
	c.JSON(http.StatusOK, serviceResp.NewAPIResponse(resp.GetBaseResp(), resp))
}
