// Code generated by hertz generator.

package Api

import (
	"my_blog/biz/middleware"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return middleware.GetRootMW()
}

func _hellomethodMw() []app.HandlerFunc {
	// your code...
	return nil
}
